### ISSUE TITLE
MacOS problems with tool's icons

### ISSUE THREAD

**Issue by janeks00** [jongough/ocpn_draw_pi#566]
Hello everyone!

I tried to use OpenCPNDraw on my MacBook Air M1 with system version 15.1.1, yet I encountered some problems with the available tools.

I tried to create a boundary of a restricted area for navigation, yet it was impossible to choose an appropriate tool with the mouse. Later, I discovered that using tab and shift+tab for selecting and space for accepting certain tools works. I am attaching a photo of how the user interface is rendering.

Thank you very much for a useful feature and your time!

![Image](https://github.com/user-attachments/assets/19652887-0d42-4fae-962f-4d248298df95)

**Comment by jongough** [comment]
The toolbar for OD tries to make a best guess at the size it needs to be from the information supplied by OCPN. You can change the size using a mouse, just position the pointer over an edge or corner and you should be able to drag it to the size you want. You should also be able to reposition it on the screen. Can you give this a go and see what happens?

**Comment by rgleason** [comment]
> You can change the size using a mouse, just position the pointer over an edge or corner and you should be able to drag it to the size you want

 did not know that Jon!  Thanks.

**Comment by jongough** [comment]
There is also a third way to change the tools and that is by right clicking. OD will cycle through the tools available with the current tool showing in the OCPN toolbar and the mouse pointer changing to be relevant to the tool. Escape or left clicking on the OCPN toolbar OD draw icon will terminate the drawing request.

**Comment by rgleason** [comment]
I think this issue is solved

**Comment by janeks00** [comment]
> The toolbar for OD tries to make a best guess at the size it needs to be from the information supplied by OCPN. You can change the size using a mouse, just position the pointer over an edge or corner and you should be able to drag it to the size you want. You should also be able to reposition it on the screen. Can you give this a go and see what happens?
> 
> I don't have a mac to try this out on, but it seems to work on older macs/software versions.

It is possible to resize a window, but icons still don't apply, take a look on pic below:

<img width="829" alt="Image" src="https://github.com/user-attachments/assets/0f3ec493-38f5-4257-9a0c-238001156db2" />

On my computer (MacBook Air M1) there is only way to use tab and shift+tab while selecting.

**Comment by janeks00** [comment]
The problem firsty occured on OpenCPN 5.6.2. version, yet after reinstalling OpenCPN to version 5.10.2 - all works correctly

**Comment by jongough** [comment]
You have to be careful if using new versions of operating systems, i.e. macOS Sequoia, to be using the latest version of OCPN and any plugins that you may want. There are changes going on continuously to make sure the software works on newer versions of operating systems. Using old versions can have issues such as you experienced.

Can you please close this issue if you are happy with the resolution>
